import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'mn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  /**
   * Look up a key in a specific language, ignoring the active one. For the few
   * places that show both languages at once (the About page) rather than
   * switching between them.
   */
  tl: (lang: Language, key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  mn: {
    // Navbar
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.cart': 'Cart',

    // Hero / Home
    'hero.title': 'Амтны төгс зохицол',
    'hero.subtitle': 'Уламжлалт болон орчин үеийн хоолны соёлыг нэг дороос',
    'hero.cta': 'Menu',
    'hero.order_now': 'Order Now',
    'hero.browse': 'Categories',
    'hero.premium': 'Premium Dining',
    'hero.hours': 'Hours',
    'hero.location': 'Location',
    'hero.quality': 'Quality',
    'hero.hours_detail': '11:00 - 19:00 (Даваа гарагт амарна)',
    'hero.location_detail': 'Дүнжингарав food court',
    'hero.quality_detail': 'Tasty and fresh',
    'hero.tagline': 'Гурван дэлхий. Нэг ширээ.',
    'hero.reservations': 'Захиалга',
    'hero.next': 'Дараах',
    'featured.title': 'Featured',
    'featured.subtitle': 'Манай хамгийн их захиалагддаг хоолнууд',

    // Menu
    'menu.title': 'Culinary Journey',
    'menu.selection': 'Our Selection',
    'menu.explore': 'Манай ертөнц',
    'menu.select_cuisine': 'Хоолоо сонгоорой',
    'menu.search': 'Search...',
    'menu.all': 'All',
    'menu.european': 'Европ хоол',
    'menu.european_desc': 'Classic continental flavors',
    'menu.asian': 'Ази хоол',
    'menu.asian_desc': 'Authentic eastern spices',
    'menu.mongolian': 'Монгол хоол',
    'menu.mongolian_desc': 'Уламжлалт амт чанар',
    'menu.specials': 'Онцгой хоол',
    'menu.specials_desc': 'Тусгай хоолнууд',
    'menu.drinks': 'Ундаа, нэмэлт',
    'menu.drinks_desc': 'Сэргээш болон нэмэлтүүд',
    'menu.add_to_cart': 'Сагсанд нэмэх',
    'menu.sold_out': 'Дууссан',
    'menu.closed': 'Хаалттай',
    'menu.no_items': 'No items found.',

    // Cart
    'cart.title': 'Cart',
    'cart.empty': 'Сагс хоосон байна',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.notes': 'Notes',
    'cart.order_type': 'Order Type',
    'cart.pickup': 'Pickup',
    'cart.at_mall': 'At Mall',
    'cart.kiosk_number': 'Kiosk #',
    'cart.customer_name': 'Name',
    'cart.phone': 'Phone',
    'cart.order_received': 'Захиалга хүлээн авлаа!',
    'cart.order_number': 'Таны захиалгын дугаар',
    'cart.order_number_desc': 'Энэ дугаарыг ашиглан тооцоогоо хийж, хоолоо аваарай.',
    'cart.order_thanks': '1ЦЭГЦ-ийг сонгосонд баярлалаа.',
    'cart.order_preparing': 'Манай тогооч нар таны хоолыг бэлтгэж байна.',
    'cart.est_time': '15-20 минут',
    'cart.back_to_menu': 'Back to Menu',
    'cart.start_adding': 'Start Adding',
    'cart.checkout_details': 'Checkout Details',
    'cart.order_option': 'Order Option',
    'cart.special_notes': 'Notes (Optional)',
    'cart.cash_only': 'Жич: Бид одоогоор зөвхөн бэлэн мөнгөөр тооцоо хийж байна.',
    'cart.payment_method': 'Төлбөрийн арга',
    'cart.payment.qpay': 'QPay',
    'cart.payment.qpay.subtitle': 'Аль ч банкны аппаас QR-аар төлөх',
    'cart.payment.qpay.confirmed': 'QPay төлбөр амжилттай! Захиалга бэлтгэгдэж байна.',
    'cart.payment.qpay.expired': 'QPay төлбөрийн хугацаа дууслаа. Захиалгаа дахин өгнө үү.',
    'cart.payment.cash': 'Бэлэн мөнгө',
    'cart.payment.bank': 'Дансаар шилжүүлэх',
    'cart.payment.bank.instructions': 'Доорх дансанд яг тэгдэг дүнг шилжүүлээд, гүйлгээний утгад жишиг кодыг бичнэ үү.',
    'cart.payment.bank.account': 'Дансны дугаар',
    'cart.payment.bank.holder': 'Дансны эзэн',
    'cart.payment.bank.amount': 'Шилжүүлэх дүн',
    'cart.payment.bank.reference': 'Гүйлгээний утга',
    'cart.payment.bank.copy': 'Хуулах',
    'cart.payment.bank.copied': 'Хуулагдлаа',
    'cart.payment.bank.warning': 'Жишиг кодыг яг ингэж бичээгүй бол захиалга баталгаажихгүй.',
    'cart.payment.awaiting': 'Төлбөр хүлээгдэж байна',
    'cart.payment.confirmed': 'Төлбөр баталгаажлаа! Захиалга бэлтгэгдэж байна.',
    'cart.payment.expired': 'Төлбөрийн хугацаа дууслаа. Захиалгаа дахин өгнө үү.',
    'cart.payment.expires_in': 'Төлбөрийн хугацаа',
    'cart.back_to_cart': 'Back to Cart',
    'cart.confirm_order': 'Confirm Order',
    'cart.proceed': 'Proceed',
    'cart.subtotal': 'Subtotal',
    'cart.success': 'Амжилттай!',
    'cart.error': 'Алдаа гарлаа.',
    'cart.closed': 'Одоогоор захиалга авах боломжгүй байна.',
    'cart.packaging': 'Сав баглаа',
    'cart.order.pickup.title': 'Таны захиалга хүлээнэ!',
    'cart.order.kiosk.title': 'Таны захиалга баталгаажлаа!',
    'cart.admin.test_mode_hint': 'Админ тест горим — хязгаарлалт идэвхгүй',
    'cart.admin.discount_label': 'Хөнгөлөлт (₮)',
    'cart.admin.zero_charge_hint': 'Нийт ₮0 — төлбөр алгасна',
    'admin.orders.test_badge': 'ТЕСТ',

    // About
    'about.eyebrow': 'Манай тухай',
    'about.title': 'Гурван дэлхий. Нэг ширээ.',
    'about.subtitle': 'Дүнжингаравт 2013 оноос хойш.',
    'about.description': '1ЦЭГЦ нь Дүнжингарав худалдааны төвийн food court нээгдсэн 2013 оноос хойш тасралтгүй ажиллаж байна. Үүсгэн байгуулагч, ерөнхий тогооч О.Батцэцэг өмнө нь тус төвийн эзний хувийн тогоочоор ажиллаж байжээ. Бид Европ, Ази, Монгол гурван орны хоолыг нэг гал тогооноос бэлтгэхээс гадна түргэн хоол, танхим болон гадна талбайн хоолны үйлчилгээ үзүүлдэг.',
    'about.story_label': 'Манай түүх',
    'about.location_label': 'Бидний байршил',
    'about.location_name': 'Дүнжингарав, Food Court',
    'about.hours_label': 'Цагийн хуваарь',
    'about.hours_value': 'Мягмар–Ням: 11:00–19:00',
    'about.closed_value': 'Даваа: Амарна',

    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': 'Бидэнтэй холбогдоорой.',
    'contact.location': 'Location',
    'contact.location.detail': 'Дүнжингарав food court',
    'contact.phone': 'Phone',
    'contact.phone_detail': '99138866',
    'contact.email': 'Email',
    'contact.email_detail': 'boldsaihan666@gmail.com',
    'contact.hours': 'Hours',
    'contact.hours.detail': 'Мягмар - Ням: 11:00 - 19:00 (Даваа гарагт амарна)',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Name',
    'contact.form.placeholder.email': 'Email',
    'contact.form.placeholder.message': 'How can we help?',
    'contact.form.send': 'Send',
    'contact.address': 'Address',

    // Admin
    'admin.title': 'Admin',
    'admin.login.title': 'Admin Login',
    'admin.login.subtitle': 'Authorized access only.',
    'admin.login.button': 'Login with Google',
    'admin.nav.menu': 'Menu',
    'admin.nav.orders': 'Orders',
    'admin.nav.staff': 'Staff',
    'admin.nav.logout': 'Logout',
    'admin.menu.title': 'Menu Manager',
    'admin.menu.subtitle': 'Add items to the Draft Pool, then move them to a category.',
    'admin.menu.add': 'Add Item',
    'admin.menu.pool.master': 'Draft Pool',
    'admin.menu.pool.empty': 'Empty',
    'admin.orders.title': 'Orders',
    'admin.orders.subtitle': 'Manage incoming orders.',
    'admin.orders.empty': 'No orders.',
    'admin.orders.id': 'Order ID',
    'admin.orders.type.pickup': 'Pickup',
    'admin.orders.type.kiosk': 'At Mall',
    'admin.orders.status.pending': 'Pending',
    'admin.orders.status.preparing': 'Preparing',
    'admin.orders.status.ready': 'Ready',
    'admin.orders.status.completed': 'Completed',
    'admin.orders.status.cancelled': 'Cancelled',
    'admin.orders.notes': 'Notes',
    'admin.orders.items': 'Items',
    'admin.orders.total': 'Total',
    'admin.orders.action.start': 'Start',
    'admin.orders.action.ready': 'Ready',
    'admin.orders.action.complete': 'Complete',
    'admin.orders.payment.method.cash': 'Бэлэн',
    'admin.orders.payment.method.bank': 'Шилжүүлэг',
    'admin.orders.payment.awaiting': 'Төлбөр хүлээж буй',
    'admin.orders.payment.confirmed': 'Төлбөр баталгаажсан',
    'admin.orders.payment.expired': 'Хугацаа дууссан',
    'admin.orders.payment.ref': 'Жишиг',
    'admin.orders.action.mark_paid': 'Төлбөр баталгаажуулах',
    'admin.orders.confirm_paid': 'Та энэ захиалгыг төлсөн гэж тэмдэглэхдээ итгэлтэй байна уу? Khan Bank-аас гүйлгээ ирсэнг шалгасан уу?',
    'admin.orders.action.mark_cash_paid': 'Бэлнээр төлсөн',
    'admin.orders.confirm_cash': 'Бэлэн мөнгийг хүлээн авсан уу? Таны нэр дээр бүртгэгдэнэ.',
    'admin.orders.paid_by': 'Баталгаажуулсан',
    'admin.orders.stats.orders': 'Захиалга',
    'admin.orders.stats.revenue': 'Баталгаажсан орлого',
    'admin.orders.stats.avg': 'Дундаж чек',
    'admin.orders.attention.title': 'Төлбөр шалгах шаардлагатай',
    'admin.orders.attention.expected': 'Нэхэмжилсэн',
    'admin.orders.attention.observed': 'Төлсөн',
    'admin.orders.search_placeholder': 'Захиалга хайх…',
    'admin.orders.new_order': 'Шинэ захиалга',
    'admin.orders.today': 'Өнөөдөр',
    'admin.orders.payment.refunded': 'Буцаагдсан',
    'admin.orders.payment.review': 'Шалгах шаардлагатай',
    'admin.orders.action.refund': 'Буцаалт хийх',
    'admin.orders.confirm_refund': 'Энэ QPay төлбөрийг буцаахдаа итгэлтэй байна уу?',
    'admin.orders.confirm.success': 'Төлбөр баталгаажлаа',
    'admin.orders.confirm.already': 'Энэ захиалгын төлбөр аль хэдийн баталгаажсан байна',
    'admin.orders.confirm.bad_state': 'Захиалга төлбөр хүлээх төлөвт байхгүй тул баталгаажуулах боломжгүй. Одоогийн төлөв',
    'admin.orders.confirm.not_found': 'Захиалга олдсонгүй',
    'admin.orders.confirm.failed': 'Төлбөр баталгаажуулж чадсангүй',
    'admin.orders.refund.success': 'Төлбөр амжилттай буцаагдлаа',
    'admin.orders.refund.p2p': 'QPay зөвхөн картын гүйлгээг автоматаар буцаадаг. Энэ дансны (P2P) төлбөрийг гар аргаар шилжүүлж буцаана уу.',
    'admin.orders.refund.failed': 'Буцаалт амжилтгүй боллоо',

    // Bank History tab
    'admin.nav.bank_history': 'Гүйлгээний түүх',
    'admin.bank.title': 'Банкны гүйлгээний түүх',
    'admin.bank.subtitle': 'Сүүлийн 7 хоногийн ирсэн гүйлгээ.',
    'admin.bank.empty': 'Сүүлийн 7 хоногт гүйлгээ алга. Гүйлгээ нэмэх товчоор бүртгэнэ үү.',
    'admin.bank.stats.today': 'Өнөөдөр',
    'admin.bank.stats.week': '7 хоног',
    'admin.bank.stats.unmatched': 'Тааруулагдаагүй',
    'admin.bank.stats.matched': 'Захиалгатай',
    'admin.bank.filter.all': 'Бүгд',
    'admin.bank.filter.unmatched': 'Тааруулагдаагүй',
    'admin.bank.filter.matched': 'Тааруулсан',
    'admin.bank.filter.7days': 'Сүүлийн 7 хоног',
    'admin.bank.col.time': 'Цаг',
    'admin.bank.col.sender': 'Илгээгч',
    'admin.bank.col.amount': 'Дүн',
    'admin.bank.col.description': 'Утга',
    'admin.bank.col.match': 'Захиалга',
    'admin.bank.match.unmatched': 'Тааруулаагүй',
    'admin.bank.match.matched': 'Тааруулсан',
    'admin.bank.match.amount_mismatch': 'Дүн зөрсөн',
    'admin.bank.match.unknown_ref': 'Жишиг олдсонгүй',
    'admin.bank.match.reconciled': 'Баталгаажсан',
    'admin.bank.action.add_manual': 'Гар оруулах',
    'admin.bank.action.confirm_order': 'Захиалга баталгаажуулах',
    'admin.bank.modal.title': 'Гүйлгээ нэмэх',
    'admin.bank.modal.amount': 'Дүн (₮)',
    'admin.bank.modal.description': 'Гүйлгээний утга',
    'admin.bank.modal.sender': 'Илгээгчийн нэр',
    'admin.bank.modal.posted_at': 'Гүйлгээ хийгдсэн цаг',
    'admin.bank.modal.save': 'Хадгалах',
    'admin.bank.source.manual': 'Гар',
    'admin.staff.title': 'Staff',
    'admin.staff.subtitle': 'Manage admin access.',
    'admin.staff.form.placeholder': 'Email...',
    'admin.staff.form.button': 'Add',
    'admin.staff.list.title': 'Admins',
    'admin.staff.primary': 'Primary',
    'admin.modal.add.title': 'Add Item',
    'admin.modal.edit.title': 'Edit Item',
    'admin.modal.form.name': 'Name',
    'admin.modal.form.category': 'Category',
    'admin.modal.form.price': 'Price',
    'admin.modal.form.description': 'Description',
    'admin.modal.form.image': 'Image',
    'admin.modal.form.available': 'Available',
    'admin.modal.form.featured': 'Featured',
    'admin.modal.form.save': 'Save',
    'admin.menu': 'Menu',
    'admin.orders': 'Orders',
    'admin.staff': 'Staff',
    'admin.logout': 'Logout',
    'admin.login': 'Login',
    'admin.add_item': 'Add Item',
    'admin.master_pool': 'Master Pool',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',

    // Footer
    'footer.description': 'Европ болон Ази хоолны төгс зохицол.',
    'footer.quick_links': 'Links',
    'footer.contact_us': 'Contact',
    'footer.opening_hours': 'Hours',
    'footer.rights': '© 2026 1ЦЭГЦ.',
    'footer.admin': 'Admin',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.mon': 'Даваа',
    'footer.tue_sun': 'Мягмар - Ням',
    'footer.closed': 'Амарна',
    'footer.location_detail': 'Дүнжингарав food court',
    'footer.phone': '99138866',
    'footer.email': 'boldsaihan666@gmail.com',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.cart': 'Cart',

    // Hero / Home
    'hero.title': 'Perfect Harmony of Taste',
    'hero.subtitle': 'Traditional and Modern Culinary Culture in One Place',
    'hero.cta': 'View Menu',
    'hero.order_now': 'Order Now',
    'hero.browse': 'Browse Categories',
    'hero.premium': 'Premium Dining Experience',
    'hero.hours': 'Opening Hours',
    'hero.location': 'Location',
    'hero.quality': 'Quality',
    'hero.hours_detail': '11:00 AM - 07:00 PM (Mon Closed)',
    'hero.location_detail': 'Dunjingarav Food Court',
    'hero.quality_detail': 'Tasty and Fresh',
    'hero.tagline': 'Three Worlds. One Table.',
    'hero.reservations': 'Reservations',
    'hero.next': 'Next',
    'featured.title': 'Featured Dishes',
    'featured.subtitle': 'Our Most Popular Selections',

    // Menu
    'menu.title': 'The Culinary Journey',
    'menu.selection': 'Our Selection',
    'menu.explore': 'Explore Our World',
    'menu.select_cuisine': 'Select Your Cuisine',
    'menu.search': 'Search dishes...',
    'menu.all': 'All',
    'menu.european': 'European',
    'menu.european_desc': 'Classic continental flavors',
    'menu.asian': 'Asian',
    'menu.asian_desc': 'Authentic eastern spices',
    'menu.mongolian': 'Mongolian',
    'menu.mongolian_desc': 'Traditional local flavors',
    'menu.specials': 'Specials',
    'menu.specials_desc': "Chef's special dishes",
    'menu.drinks': 'Drinks and Extra',
    'menu.drinks_desc': 'Refreshing beverages and extras',
    'menu.add_to_cart': 'Add to Cart',
    'menu.sold_out': 'Sold Out',
    'menu.closed': 'Closed',
    'menu.no_items': 'No items found in this category.',

    // Cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.notes': 'Notes',
    'cart.order_type': 'Order Type',
    'cart.pickup': 'Pickup',
    'cart.at_mall': 'At Mall',
    'cart.kiosk_number': 'Kiosk Number',
    'cart.customer_name': 'Name',
    'cart.phone': 'Phone',
    'cart.order_received': 'Order Received!',
    'cart.order_number': 'Your Order Number',
    'cart.order_number_desc': 'Use this number to pay and pick up your order.',
    'cart.order_thanks': 'Thank you for choosing 1ЦЭГЦ.',
    'cart.order_preparing': 'Our chefs are preparing your meal.',
    'cart.est_time': 'Estimated time: 15-20 mins',
    'cart.back_to_menu': 'Back to Menu',
    'cart.start_adding': 'Start Adding Dishes',
    'cart.checkout_details': 'Checkout Details',
    'cart.order_option': 'Order Option',
    'cart.special_notes': 'Special Notes (Optional)',
    'cart.cash_only': 'Note: We currently only accept Cash on Pickup/at Location. Online payments coming soon!',
    'cart.payment_method': 'Payment Method',
    'cart.payment.qpay': 'QPay',
    'cart.payment.qpay.subtitle': 'Pay with any bank app via QR',
    'cart.payment.qpay.confirmed': 'QPay payment confirmed! Your order is being prepared.',
    'cart.payment.qpay.expired': 'QPay payment window expired. Please reorder.',
    'cart.payment.cash': 'Cash',
    'cart.payment.bank': 'Bank Transfer',
    'cart.payment.bank.instructions': 'Transfer the exact amount below to this account, and put the reference code in the transfer description.',
    'cart.payment.bank.account': 'Account Number',
    'cart.payment.bank.holder': 'Account Holder',
    'cart.payment.bank.amount': 'Amount',
    'cart.payment.bank.reference': 'Reference Code',
    'cart.payment.bank.copy': 'Copy',
    'cart.payment.bank.copied': 'Copied!',
    'cart.payment.bank.warning': 'Without the exact reference code, we cannot confirm your order.',
    'cart.payment.awaiting': 'Awaiting Payment',
    'cart.payment.confirmed': 'Payment confirmed! Your order is being prepared.',
    'cart.payment.expired': 'Payment window expired. Please reorder.',
    'cart.payment.expires_in': 'Payment window',
    'cart.back_to_cart': 'Back to Cart',
    'cart.confirm_order': 'Confirm Order',
    'cart.proceed': 'Proceed to Checkout',
    'cart.subtotal': 'Subtotal',
    'cart.success': 'Order placed successfully!',
    'cart.error': 'Failed to place order. Please try again.',
    'cart.closed': 'Web ordering is currently closed.',
    'cart.packaging': 'Packaging',
    'cart.order.pickup.title': 'Verify Your Order!',
    'cart.order.kiosk.title': 'Payment Required!',
    'cart.admin.test_mode_hint': 'Admin test mode — restrictions bypassed',
    'cart.admin.discount_label': 'Admin discount (₮)',
    'cart.admin.zero_charge_hint': 'Total ₮0 — payment skipped',
    'admin.orders.test_badge': 'TEST',

    // About
    'about.eyebrow': 'About Us',
    'about.title': 'Three Worlds. One Table.',
    'about.subtitle': 'At Dunjingarav since 2013.',
    'about.description': '1ЦЭГЦ has cooked at Dunjingarav since 2013 — since the day the food court first opened. Our founder and head chef, O. Battsetseg, previously worked as personal chef to the owner of the shopping centre. We cook European, Asian and Mongolian dishes in one kitchen, and also serve fast food and cater both indoors and outdoors.',
    'about.story_label': 'Our Story',
    'about.location_label': 'Find Us',
    'about.hours_label': 'Opening Hours',
    'about.hours_value': 'Tue – Sun: 11:00 – 19:00',
    'about.closed_value': 'Monday: Closed',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': "We'd love to hear from you. Visit us at Central Mall or reach out online.",
    'contact.location': 'Location',
    'contact.location.detail': 'Dunjingarav Food Court',
    'contact.phone': 'Phone',
    'contact.phone_detail': '99138866',
    'contact.email': 'Email',
    'contact.email_detail': 'boldsaihan666@gmail.com',
    'contact.hours': 'Hours',
    'contact.hours.detail': 'Tue - Sun: 11:00 AM - 07:00 PM (Closed on Monday)',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Your Name',
    'contact.form.placeholder.email': 'your@email.com',
    'contact.form.placeholder.message': 'How can we help?',
    'contact.form.send': 'Send Message',
    'contact.address': 'Address',

    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.login.title': 'Admin Portal',
    'admin.login.subtitle': 'Please sign in with an authorized account to manage the restaurant.',
    'admin.login.button': 'Sign In with Google',
    'admin.nav.menu': 'Menu Manager',
    'admin.nav.orders': 'Orders',
    'admin.nav.staff': 'Staff Management',
    'admin.nav.logout': 'Logout',
    'admin.menu.title': 'Menu Manager',
    'admin.menu.subtitle': 'Add items to the Draft Pool, then move them to a category.',
    'admin.menu.add': 'Add Item',
    'admin.menu.pool.master': 'Draft Pool',
    'admin.menu.pool.empty': 'Empty Pool',
    'admin.orders.title': 'Orders',
    'admin.orders.subtitle': 'Manage incoming orders and track preparation status.',
    'admin.orders.empty': 'No orders yet.',
    'admin.orders.id': 'Order ID',
    'admin.orders.type.pickup': 'Pickup',
    'admin.orders.type.kiosk': 'At Mall',
    'admin.orders.status.pending': 'Pending',
    'admin.orders.status.preparing': 'Preparing',
    'admin.orders.status.ready': 'Ready',
    'admin.orders.status.completed': 'Completed',
    'admin.orders.status.cancelled': 'Cancelled',
    'admin.orders.notes': 'Notes',
    'admin.orders.items': 'Items',
    'admin.orders.total': 'Total',
    'admin.orders.action.start': 'Start Preparing',
    'admin.orders.action.ready': 'Mark Ready',
    'admin.orders.action.complete': 'Complete',
    'admin.orders.payment.method.cash': 'Cash',
    'admin.orders.payment.method.bank': 'Bank Transfer',
    'admin.orders.payment.awaiting': 'Awaiting Payment',
    'admin.orders.payment.confirmed': 'Paid',
    'admin.orders.payment.expired': 'Payment Expired',
    'admin.orders.payment.ref': 'Ref',
    'admin.orders.action.mark_paid': 'Mark Paid',
    'admin.orders.confirm_paid': 'Are you sure you want to mark this order as paid? Have you verified the transfer in your Khan Bank app?',
    'admin.orders.action.mark_cash_paid': 'Paid in cash',
    'admin.orders.confirm_cash': 'Did you receive the cash? This will be recorded under your name.',
    'admin.orders.paid_by': 'Confirmed by',
    'admin.orders.stats.orders': 'Orders',
    'admin.orders.stats.revenue': 'Confirmed revenue',
    'admin.orders.stats.avg': 'Avg ticket',
    'admin.orders.attention.title': 'Payments needing review',
    'admin.orders.attention.expected': 'Billed',
    'admin.orders.attention.observed': 'Paid',
    'admin.orders.search_placeholder': 'Search orders…',
    'admin.orders.new_order': 'New Order',
    'admin.orders.today': 'Today',
    'admin.orders.payment.refunded': 'Refunded',
    'admin.orders.payment.review': 'Needs review',
    'admin.orders.action.refund': 'Refund',
    'admin.orders.confirm_refund': 'Refund this QPay payment?',
    'admin.orders.confirm.success': 'Payment confirmed',
    'admin.orders.confirm.already': 'This order was already confirmed',
    'admin.orders.confirm.bad_state': 'Order is not awaiting payment, so it cannot be confirmed. Current state',
    'admin.orders.confirm.not_found': 'Order not found',
    'admin.orders.confirm.failed': 'Could not confirm payment',
    'admin.orders.refund.success': 'Payment refunded',
    'admin.orders.refund.p2p': 'QPay only auto-refunds card payments. Refund this bank (P2P) payment with a manual transfer.',
    'admin.orders.refund.failed': 'Refund failed',

    // Bank History tab
    'admin.nav.bank_history': 'Bank History',
    'admin.bank.title': 'Bank Transfer History',
    'admin.bank.subtitle': 'Last 7 days of incoming credits.',
    'admin.bank.empty': 'No transactions in the last 7 days. Use Add Transaction to record one.',
    'admin.bank.stats.today': 'Today',
    'admin.bank.stats.week': '7 days',
    'admin.bank.stats.unmatched': 'Unmatched',
    'admin.bank.stats.matched': 'With order',
    'admin.bank.filter.all': 'All',
    'admin.bank.filter.unmatched': 'Unmatched',
    'admin.bank.filter.matched': 'Matched',
    'admin.bank.filter.7days': 'Last 7 days',
    'admin.bank.col.time': 'Time',
    'admin.bank.col.sender': 'Sender',
    'admin.bank.col.amount': 'Amount',
    'admin.bank.col.description': 'Description',
    'admin.bank.col.match': 'Order',
    'admin.bank.match.unmatched': 'Unmatched',
    'admin.bank.match.matched': 'Matched',
    'admin.bank.match.amount_mismatch': 'Amount differs',
    'admin.bank.match.unknown_ref': 'Unknown ref',
    'admin.bank.match.reconciled': 'Confirmed',
    'admin.bank.action.add_manual': 'Add Manually',
    'admin.bank.action.confirm_order': 'Confirm Order',
    'admin.bank.modal.title': 'Add Transaction',
    'admin.bank.modal.amount': 'Amount (₮)',
    'admin.bank.modal.description': 'Description / Memo',
    'admin.bank.modal.sender': 'Sender Name',
    'admin.bank.modal.posted_at': 'Transaction Time',
    'admin.bank.modal.save': 'Save',
    'admin.bank.source.manual': 'Manual',
    'admin.staff.title': 'Staff Management',
    'admin.staff.subtitle': 'Authorize additional email addresses to access this admin portal.',
    'admin.staff.form.placeholder': 'Enter admin email...',
    'admin.staff.form.button': 'Authorize',
    'admin.staff.list.title': 'Authorized Admins',
    'admin.staff.primary': 'Primary',
    'admin.modal.add.title': 'Add New Item',
    'admin.modal.edit.title': 'Edit Menu Item',
    'admin.modal.form.name': 'Item Name',
    'admin.modal.form.category': 'Category',
    'admin.modal.form.price': 'Price',
    'admin.modal.form.description': 'Description',
    'admin.modal.form.image': 'Image URL',
    'admin.modal.form.available': 'Available',
    'admin.modal.form.featured': 'Featured',
    'admin.modal.form.save': 'Save Changes',

    // Footer
    'footer.description': 'Experience the perfect harmony of European elegance and Asian vibrancy. Fresh ingredients, authentic recipes, and a passion for culinary excellence.',
    'footer.quick_links': 'Quick Links',
    'footer.contact_us': 'Contact Us',
    'footer.opening_hours': 'Opening Hours',
    'footer.rights': '© 2026 1ЦЭГЦ. All rights reserved.',
    'footer.admin': 'Admin',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.mon': 'Monday',
    'footer.tue_sun': 'Tue - Sunday',
    'footer.closed': 'Closed',
    'footer.location_detail': 'Dunjingarav Food Court',
    'footer.phone': '99138866',
    'footer.email': 'boldsaihan666@gmail.com',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('mn'); // Default to Mongolian

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const tl = (lang: Language, key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
