import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'mn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  mn: {
    // Navbar
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.cart': 'Cart',

    // Hero / Home
    'hero.title': 'Амтны төгс зохицол',
    'hero.subtitle': 'Уламжлалт болон орчин үеийн хоолны соёлыг нэг дороос',
    'hero.cta': 'Menu',
    'hero.order_now': 'Order Now',
    'hero.browse': 'Categories',
    'hero.premium': 'Premium Dining',
    'hero.hours': 'Hours',
    'hero.location': 'Location',
    'hero.quality': 'Quality',
    'hero.hours_detail': '11:00 - 19:00 (Даваа гарагт амарна)',
    'hero.location_detail': 'Дүнжингарав food court',
    'hero.quality_detail': 'Tasty and fresh',
    'hero.next': 'Дараах',
    'featured.title': 'Featured',
    'featured.subtitle': 'Манай хамгийн их захиалагддаг хоолнууд',

    // Menu
    'menu.title': 'Culinary Journey',
    'menu.selection': 'Our Selection',
    'menu.search': 'Search...',
    'menu.all': 'All',
    'menu.european': 'Европ хоол',
    'menu.european_desc': 'Classic continental flavors',
    'menu.asian': 'Ази хоол',
    'menu.asian_desc': 'Authentic eastern spices',
    'menu.mongolian': 'Монгол хоол',
    'menu.mongolian_desc': 'Уламжлалт амт чанар',
    'menu.drinks': 'Ундаа, нэмэлт',
    'menu.drinks_desc': 'Сэргээш болон нэмэлтүүд',
    'menu.add_to_cart': 'Сагсанд нэмэх',
    'menu.sold_out': 'Дууссан',
    'menu.closed': 'Хаалттай',
    'menu.no_items': 'No items found.',

    // Cart
    'cart.title': 'Cart',
    'cart.empty': 'Сагс хоосон байна',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.notes': 'Notes',
    'cart.order_type': 'Order Type',
    'cart.pickup': 'Pickup',
    'cart.at_mall': 'At Mall',
    'cart.kiosk_number': 'Kiosk #',
    'cart.customer_name': 'Name',
    'cart.phone': 'Phone',
    'cart.order_received': 'Захиалга хүлээн авлаа!',
    'cart.order_number': 'Таны захиалгын дугаар',
    'cart.order_number_desc': 'Энэ дугаарыг ашиглан тооцоогоо хийж, хоолоо аваарай.',
    'cart.order_thanks': '1ЦЭГЦ-ийг сонгосонд баярлалаа.',
    'cart.order_preparing': 'Манай тогооч нар таны хоолыг бэлтгэж байна.',
    'cart.est_time': '15-20 минут',
    'cart.back_to_menu': 'Back to Menu',
    'cart.start_adding': 'Start Adding',
    'cart.checkout_details': 'Checkout Details',
    'cart.order_option': 'Order Option',
    'cart.special_notes': 'Notes (Optional)',
    'cart.cash_only': 'Жич: Бид одоогоор зөвхөн бэлэн мөнгөөр тооцоо хийж байна.',
    'cart.back_to_cart': 'Back to Cart',
    'cart.confirm_order': 'Confirm Order',
    'cart.proceed': 'Proceed',
    'cart.subtotal': 'Subtotal',
    'cart.success': 'Амжилттай!',
    'cart.error': 'Алдаа гарлаа.',
    'cart.closed': 'Одоогоор захиалга авах боломжгүй байна.',
    'cart.packaging': 'Сав баглаа',
    'cart.order.pickup.title': 'Таны захиалга хүлээнэ!',
    'cart.order.kiosk.title': 'Таны захиалга баталгаажлаа!',

    // About
    'about.title': 'About Us',
    'about.subtitle': 'Art of Cooking',
    'about.description': '1ЦЭГЦ нь Европын тансаг амт болон Азийн хурц амтлагчийн хооронд сонголт хийх хосгүй боломжийг олгож байна.',

    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': 'Бидэнтэй холбогдоорой.',
    'contact.location': 'Location',
    'contact.location.detail': 'Дүнжингарав food court',
    'contact.phone': 'Phone',
    'contact.phone_detail': '99138866',
    'contact.email': 'Email',
    'contact.hours': 'Hours',
    'contact.hours.detail': 'Мягмар - Ням: 11:00 - 19:00 (Даваа гарагт амарна)',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Name',
    'contact.form.placeholder.email': 'Email',
    'contact.form.placeholder.message': 'How can we help?',
    'contact.form.send': 'Send',
    'contact.address': 'Address',

    // Admin
    'admin.title': 'Admin',
    'admin.login.title': 'Admin Login',
    'admin.login.subtitle': 'Authorized access only.',
    'admin.login.button': 'Login with Google',
    'admin.nav.menu': 'Menu',
    'admin.nav.orders': 'Orders',
    'admin.nav.staff': 'Staff',
    'admin.nav.logout': 'Logout',
    'admin.menu.title': 'Menu Manager',
    'admin.menu.subtitle': 'Drag and drop items to categories.',
    'admin.menu.add': 'Add Item',
    'admin.menu.pool.master': 'Master Pool',
    'admin.menu.pool.empty': 'Empty',
    'admin.orders.title': 'Orders',
    'admin.orders.subtitle': 'Manage incoming orders.',
    'admin.orders.empty': 'No orders.',
    'admin.orders.id': 'Order ID',
    'admin.orders.type.pickup': 'Pickup',
    'admin.orders.type.kiosk': 'At Mall',
    'admin.orders.status.pending': 'Pending',
    'admin.orders.status.preparing': 'Preparing',
    'admin.orders.status.ready': 'Ready',
    'admin.orders.status.completed': 'Completed',
    'admin.orders.status.cancelled': 'Cancelled',
    'admin.orders.notes': 'Notes',
    'admin.orders.items': 'Items',
    'admin.orders.total': 'Total',
    'admin.orders.action.start': 'Start',
    'admin.orders.action.ready': 'Ready',
    'admin.orders.action.complete': 'Complete',
    'admin.staff.title': 'Staff',
    'admin.staff.subtitle': 'Manage admin access.',
    'admin.staff.form.placeholder': 'Email...',
    'admin.staff.form.button': 'Add',
    'admin.staff.list.title': 'Admins',
    'admin.staff.primary': 'Primary',
    'admin.modal.add.title': 'Add Item',
    'admin.modal.edit.title': 'Edit Item',
    'admin.modal.form.name': 'Name',
    'admin.modal.form.category': 'Category',
    'admin.modal.form.price': 'Price',
    'admin.modal.form.description': 'Description',
    'admin.modal.form.image': 'Image',
    'admin.modal.form.available': 'Available',
    'admin.modal.form.featured': 'Featured',
    'admin.modal.form.save': 'Save',
    'admin.menu': 'Menu',
    'admin.orders': 'Orders',
    'admin.staff': 'Staff',
    'admin.logout': 'Logout',
    'admin.login': 'Login',
    'admin.add_item': 'Add Item',
    'admin.master_pool': 'Master Pool',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',

    // Footer
    'footer.description': 'Европ болон Ази хоолны төгс зохицол.',
    'footer.quick_links': 'Links',
    'footer.contact_us': 'Contact',
    'footer.opening_hours': 'Hours',
    'footer.rights': '© 2026 1ЦЭГЦ.',
    'footer.admin': 'Admin',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.mon': 'Даваа',
    'footer.tue_sun': 'Мягмар - Ням',
    'footer.closed': 'Амарна',
    'footer.location_detail': 'Дүнжингарав food court',
    'footer.phone': '99138866',
    'footer.email': 'hello@1tsegts.com',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.cart': 'Cart',

    // Hero / Home
    'hero.title': 'Perfect Harmony of Taste',
    'hero.subtitle': 'Traditional and Modern Culinary Culture in One Place',
    'hero.cta': 'View Menu',
    'hero.order_now': 'Order Now',
    'hero.browse': 'Browse Categories',
    'hero.premium': 'Premium Dining Experience',
    'hero.hours': 'Opening Hours',
    'hero.location': 'Location',
    'hero.quality': 'Quality',
    'hero.hours_detail': '11:00 AM - 07:00 PM (Mon Closed)',
    'hero.location_detail': 'Dunjingarav Food Court',
    'hero.quality_detail': 'Tasty and Fresh',
    'hero.next': 'Next',
    'featured.title': 'Featured Dishes',
    'featured.subtitle': 'Our Most Popular Selections',

    // Menu
    'menu.title': 'The Culinary Journey',
    'menu.selection': 'Our Selection',
    'menu.search': 'Search dishes...',
    'menu.all': 'All',
    'menu.european': 'European',
    'menu.european_desc': 'Classic continental flavors',
    'menu.asian': 'Asian',
    'menu.asian_desc': 'Authentic eastern spices',
    'menu.mongolian': 'Mongolian',
    'menu.mongolian_desc': 'Traditional local flavors',
    'menu.drinks': 'Drinks and Extra',
    'menu.drinks_desc': 'Refreshing beverages and extras',
    'menu.add_to_cart': 'Add to Cart',
    'menu.sold_out': 'Sold Out',
    'menu.closed': 'Closed',
    'menu.no_items': 'No items found in this category.',

    // Cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.notes': 'Notes',
    'cart.order_type': 'Order Type',
    'cart.pickup': 'Pickup',
    'cart.at_mall': 'At Mall',
    'cart.kiosk_number': 'Kiosk Number',
    'cart.customer_name': 'Name',
    'cart.phone': 'Phone',
    'cart.order_received': 'Order Received!',
    'cart.order_number': 'Your Order Number',
    'cart.order_number_desc': 'Use this number to pay and pick up your order.',
    'cart.order_thanks': 'Thank you for choosing 1ЦЭГЦ.',
    'cart.order_preparing': 'Our chefs are preparing your meal.',
    'cart.est_time': 'Estimated time: 15-20 mins',
    'cart.back_to_menu': 'Back to Menu',
    'cart.start_adding': 'Start Adding Dishes',
    'cart.checkout_details': 'Checkout Details',
    'cart.order_option': 'Order Option',
    'cart.special_notes': 'Special Notes (Optional)',
    'cart.cash_only': 'Note: We currently only accept Cash on Pickup/at Location. Online payments coming soon!',
    'cart.back_to_cart': 'Back to Cart',
    'cart.confirm_order': 'Confirm Order',
    'cart.proceed': 'Proceed to Checkout',
    'cart.subtotal': 'Subtotal',
    'cart.success': 'Order placed successfully!',
    'cart.error': 'Failed to place order. Please try again.',
    'cart.closed': 'Web ordering is currently closed.',
    'cart.packaging': 'Packaging',
    'cart.order.pickup.title': 'Verify Your Order!',
    'cart.order.kiosk.title': 'Payment Required!',

    // About
    'about.title': 'Our Story',
    'about.subtitle': 'Art of Cooking and Love',
    'about.description': '1ЦЭГЦ was born from a simple idea: why choose between the refined flavors of Europe and the bold spices of Asia? Located in the heart of Central Mall, we bring a unique fusion dining experience to busy shoppers and food enthusiasts alike.',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': "We'd love to hear from you. Visit us at Central Mall or reach out online.",
    'contact.location': 'Location',
    'contact.location.detail': 'Dunjingarav Food Court',
    'contact.phone': 'Phone',
    'contact.phone_detail': '99138866',
    'contact.email': 'Email',
    'contact.hours': 'Hours',
    'contact.hours.detail': 'Tue - Sun: 11:00 AM - 07:00 PM (Closed on Monday)',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Your Name',
    'contact.form.placeholder.email': 'your@email.com',
    'contact.form.placeholder.message': 'How can we help?',
    'contact.form.send': 'Send Message',
    'contact.address': 'Address',

    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.login.title': 'Admin Portal',
    'admin.login.subtitle': 'Please sign in with an authorized account to manage the restaurant.',
    'admin.login.button': 'Sign In with Google',
    'admin.nav.menu': 'Menu Manager',
    'admin.nav.orders': 'Orders',
    'admin.nav.staff': 'Staff Management',
    'admin.nav.logout': 'Logout',
    'admin.menu.title': 'Menu Manager',
    'admin.menu.subtitle': 'Add items to the Master Pool, then drag them to categories.',
    'admin.menu.add': 'Add Item',
    'admin.menu.pool.master': 'Master Pool',
    'admin.menu.pool.empty': 'Empty Pool',
    'admin.orders.title': 'Orders',
    'admin.orders.subtitle': 'Manage incoming orders and track preparation status.',
    'admin.orders.empty': 'No orders yet.',
    'admin.orders.id': 'Order ID',
    'admin.orders.type.pickup': 'Pickup',
    'admin.orders.type.kiosk': 'At Mall',
    'admin.orders.status.pending': 'Pending',
    'admin.orders.status.preparing': 'Preparing',
    'admin.orders.status.ready': 'Ready',
    'admin.orders.status.completed': 'Completed',
    'admin.orders.status.cancelled': 'Cancelled',
    'admin.orders.notes': 'Notes',
    'admin.orders.items': 'Items',
    'admin.orders.total': 'Total',
    'admin.orders.action.start': 'Start Preparing',
    'admin.orders.action.ready': 'Mark Ready',
    'admin.orders.action.complete': 'Complete',
    'admin.staff.title': 'Staff Management',
    'admin.staff.subtitle': 'Authorize additional email addresses to access this admin portal.',
    'admin.staff.form.placeholder': 'Enter admin email...',
    'admin.staff.form.button': 'Authorize',
    'admin.staff.list.title': 'Authorized Admins',
    'admin.staff.primary': 'Primary',
    'admin.modal.add.title': 'Add New Item',
    'admin.modal.edit.title': 'Edit Menu Item',
    'admin.modal.form.name': 'Item Name',
    'admin.modal.form.category': 'Category',
    'admin.modal.form.price': 'Price',
    'admin.modal.form.description': 'Description',
    'admin.modal.form.image': 'Image URL',
    'admin.modal.form.available': 'Available',
    'admin.modal.form.featured': 'Featured',
    'admin.modal.form.save': 'Save Changes',

    // Footer
    'footer.description': 'Experience the perfect harmony of European elegance and Asian vibrancy. Fresh ingredients, authentic recipes, and a passion for culinary excellence.',
    'footer.quick_links': 'Quick Links',
    'footer.contact_us': 'Contact Us',
    'footer.opening_hours': 'Opening Hours',
    'footer.rights': '© 2026 1ЦЭГЦ. All rights reserved.',
    'footer.admin': 'Admin',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.mon': 'Monday',
    'footer.tue_sun': 'Tue - Sunday',
    'footer.closed': 'Closed',
    'footer.location_detail': 'Dunjingarav Food Court',
    'footer.phone': '99138866',
    'footer.email': 'hello@1tsegts.com',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('mn'); // Default to Mongolian

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
